version: '3'
services:
  postgres:
    image: 'timescale/timescaledb:latest-pg14'
    restart: always
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  tectonicdb:
    image: "yurikoval/tectonicdb"
    ports:
      - "9001:9001"
    restart: on-failure
    environment:
      - TDB_LOG_FILE_NAME=/dev/null
      - TDB_DTF_FOLDER=/export/db
    command: /usr/local/bin/tdb-server -vv
    volumes:
      - 'tectonicdb_data:/export/db'

volumes:
  postgres_data:
  tectonicdb_data:
