# fly.toml app configuration file generated for oliya on 2023-07-14T14:06:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oliya"
primary_region = "sin"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
